### PR TITLE
Relax requests dependency allowing upgrades

### PR DESCRIPTION
**Pull request by soulrebel**
Tested with requests 2.18.4.

Fixes https://github.com/dubner/pytest-testrail/issues/26

### CODE REVIEW

**Comment by dubner** [comment]
@soulrebel Sorry for the delay, if you can fix the conflicts. Happy for this to be merged.

**Comment by davidemoro** [comment]
setup.py should not pin an exact version of a library's dependencies, if needed >=, >, etc operators could be used.
This breaks https://github.com/tierratelematics/cookiecutter-qa/pull/178 for example

**Comment by soulrebel** [comment]
I fixed the conflict, but since other versions were pinned I had to unpin them as well. 

It is better to keep the ``setup.py`` with the complete range of supported versions or an approximation thereof, so that you allow your user to have their own versions of the libraries. 

Then for local development instead you pin the version of all libraries in the txt file so that you test on a reproducible environment.
This is what I did in this second commit.

**Comment by dubner** [comment]
@soulrebel Can you bump version please, to force a new release

**Comment by dubner** [comment]
Thanks for your contribution :)

**Pull request merged**
